### ISSUE TITLE
Error occuring when running pretrained model trained on PURE and tested on UBFC with PhysNet

### ISSUE THREAD

**Issue by Bhupendra589** [ubicomplab/rPPG-Toolbox#171]
```
Preprocessing dataset...
  0%|                                                                                                                                                                                       | 0/2 [00:00<?, ?it/s]Warning: More than one faces are detected(Only cropping the biggest one.)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:35<00:00, 17.57s/it]
Total Number of raw files preprocessed: 2

Cached Data Path C:\Users\bsing.BHUPI\Desktop\pyt\rPPG-Toolbox-main\cached\UBFC-rPPG_SizeW72_SizeH72_ClipLength128_DataTypeDiffNormalized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len32_Median_face_boxFalse

File List Path C:\Users\bsing.BHUPI\Desktop\pyt\rPPG-Toolbox-main\cached\DataFileLists\UBFC-rPPG_SizeW72_SizeH72_ClipLength128_DataTypeDiffNormalized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len32_Median_face_boxFalse_0.0_1.0.csv
 test Preprocessed Dataset Length: 27

C:\Users\bsing.BHUPI\anaconda3\envs\rppg-toolbox\lib\site-packages\torch\utils\data\dataloader.py:560: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 12 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(

===Testing===
Testing uses pretrained model!
./final_model_release/PURE_PhysNet_DiffNormalized.pth

100%|█████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
FFT MAE (FFT Label): 0.0 +/- 0.0
FFT RMSE (FFT Label): 0.0 +/- 0.0
FFT MAPE (FFT Label): 0.0 +/- 0.0
C:\Users\bsing.BHUPI\anaconda3\envs\rppg-toolbox\lib\site-packages\numpy\lib\function_base.py:2829: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
FFT Pearson (FFT Label): nan +/- nan
FFT SNR (FFT Label): -1.496827352337295 +/- 1.9491494704719077 (dB)
```

**Comment by yahskapar** [comment]
Hi @Bhupendra589,

Can you check the dataset file path you are pointing to in your respective config file actually contains the UBFC-rPPG dataset you are trying to work with? 

Based on your terminal output, the dataset likely isn't there. I say this because the "Preprocessing dataset..." step reports there are only two raw files to process, when there should be 42 for UBFC-rPPG.

**Comment by Bhupendra589** [comment]
I again ran the code FFT Pearson (FFT Label): nan +/- nan

```
===Testing===
Testing uses pretrained model!
./final_model_release/PURE_PhysNet_DiffNormalized.pth

100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
FFT MAE (FFT Label): 3.515625 +/- 0.0
FFT RMSE (FFT Label): 3.515625 +/- 0.0
FFT MAPE (FFT Label): 3.9603960396039604 +/- 0.0
C:\Users\bsing.BHUPI\anaconda3\envs\rppg-toolbox\lib\site-packages\numpy\lib\function_base.py:2821: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\bsing.BHUPI\anaconda3\envs\rppg-toolbox\lib\site-packages\numpy\lib\function_base.py:2680: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
C:\Users\bsing.BHUPI\anaconda3\envs\rppg-toolbox\lib\site-packages\numpy\lib\function_base.py:2680: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
FFT Pearson (FFT Label): nan +/- nan
FFT SNR (FFT Label): -1.573720918008266 +/- 0.0 (dB)
```

**Comment by Bhupendra589** [comment]
1. PURE_UBFC-rPPG_PHYSNET_BASIC.yaml file

```
BASE: ['']
TOOLBOX_MODE: "only_test"  # "train_and_test"  or "only_test"
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson', 'SNR']
  USE_LAST_EPOCH: True
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: true                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: C:\Users\bsing.BHUPI\Desktop\pyt\rPPG-Toolbox-main\data\UBFC                    # Raw dataset path, need to be updated
    CACHED_PATH: C:\Users\bsing.BHUPI\Desktop\pyt\rPPG-Toolbox-main\cached  # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['DiffNormalized']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128                 #only support for factor of 512
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Physnet
  PHYSNET:
    FRAME_NUM: 128
INFERENCE:
  BATCH_SIZE: 1
  EVALUATION_METHOD: FFT        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: ./final_model_release/PURE_PhysNet_DiffNormalized.pth

```
2. In my data path it is there and the way readme says like that only , but I have just one video because if I increase that it says cuda memory error
