### ISSUE TITLE
ValueError: cannot reshape array of size 61936 into shape (180,72,72,6)

### ISSUE THREAD

**Issue by pedrombmachado** [ubicomplab/rPPG-Toolbox#175]
Dear rPPG-Toolbox team,
  I am attempting to test on the UBFC-rPPG but I am getting the error `ValueError: cannot reshape array of size 61936 into shape (180,72,72,6)`. I am inclined to think that it might be my dataset but nevertheless I would like your opinion.
The Yaml configuration file is as follows
```
BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 9e-3
  MODEL_FILE_NAME: UBFC_UBFC_deepphys
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/laura/datasets/UBFC_rPPG/DATASET_2"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/media/laura/datasets/UBFC_rPPG/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True                 # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/laura/datasets/UBFC_rPPG/DATASET_2"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/media/laura/datasets/UBFC_rPPG/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: False
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson', 'SNR']
  USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/laura/datasets/UBFC_rPPG/DATASET_2"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/media/laura/datasets/UBFC_rPPG/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.21
    END: 0.4
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: DeepPhys
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: ""
``` 
The content of  the dataset folder is
```
$ tree DATASET_2
DATASET_2
├── subject1
│   ├── ground_truth.txt
│   └── vid.avi
├── subject10
│   ├── ground_truth.txt
│   └── vid.avi
├── subject11
│   ├── ground_truth.txt
│   └── vid.avi
├── subject12
│   ├── ground_truth.txt
│   └── vid.avi
├── subject13
│   ├── ground_truth.txt
│   └── vid.avi
├── subject14
│   ├── ground_truth.txt
│   └── vid.avi
├── subject15
│   ├── ground_truth.txt
│   └── vid.avi
├── subject16
│   ├── ground_truth.txt
│   └── vid.avi
├── subject17
│   ├── ground_truth.txt
│   └── vid.avi
├── subject18
│   ├── ground_truth.txt
│   └── vid.avi
├── subject20
│   ├── ground_truth.txt
│   └── vid.avi
├── subject22
│   ├── ground_truth.txt
│   └── vid.avi
├── subject23
│   ├── ground_truth.txt
│   └── vid.avi
├── subject24
│   ├── ground_truth.txt
│   └── vid.avi
├── subject25
│   ├── ground_truth.txt
│   └── vid.avi
├── subject26
│   ├── ground_truth.txt
│   └── vid.avi
├── subject27
│   ├── ground_truth.txt
│   └── vid.avi
├── subject3
│   ├── ground_truth.txt
│   └── vid.avi
├── subject30
│   ├── ground_truth.txt
│   └── vid.avi
├── subject31
│   ├── ground_truth.txt
│   └── vid.avi
├── subject32
│   ├── ground_truth.txt
│   └── vid.avi
├── subject33
│   ├── ground_truth.txt
│   └── vid.avi
├── subject34
│   ├── ground_truth.txt
│   └── vid.avi
├── subject35
│   ├── ground_truth.txt
│   └── vid.avi
├── subject36
│   ├── ground_truth.txt
│   └── vid.avi
├── subject37
│   ├── ground_truth.txt
│   └── vid.avi
├── subject38
│   ├── ground_truth.txt
│   └── vid.avi
├── subject39
│   ├── ground_truth.txt
│   └── vid.avi
├── subject4
│   ├── ground_truth.txt
│   └── vid.avi
├── subject40
│   ├── ground_truth.txt
│   └── vid.avi
├── subject41
│   ├── ground_truth.txt
│   └── vid.avi
├── subject42
│   ├── ground_truth.txt
│   └── vid.avi
├── subject43
│   ├── ground_truth.txt
│   └── vid.avi
├── subject44
│   ├── ground_truth.txt
│   └── vid.avi
├── subject45
│   ├── ground_truth.txt
│   └── vid.avi
├── subject46
│   ├── ground_truth.txt
│   └── vid.avi
├── subject47
│   ├── ground_truth.txt
│   └── vid.avi
├── subject48
│   ├── ground_truth.txt
│   └── vid.avi
├── subject49
│   ├── ground_truth.txt
│   └── vid.avi
├── subject5
│   ├── ground_truth.txt
│   └── vid.avi
├── subject8
│   ├── ground_truth.txt
│   └── vid.avi
└── subject9
    ├── ground_truth.txt
    └── vid.avi
```
Error message
```
$ python main.py --config_file ./configs/train_configs/UBFC-rPPG_PHYSNET_laura.yaml
=> Merging a config file from ./configs/train_configs/UBFC-rPPG_PHYSNET_laura.yaml
Configuration:
BASE: ['']
DEVICE: cuda:0
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: FFT
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 10
  MODEL_PATH: 
LOG:
  PATH: runs/exp/
MODEL:
  BIGSMALL:
    FRAME_DEPTH: 3
  DROP_RATE: 0.2
  EFFICIENTPHYS:
    FRAME_DEPTH: 10
  MODEL_DIR: PreTrainedModels/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse
  NAME: DeepPhys
  PHYSNET:
    FRAME_NUM: 64
  RESUME: 
  TSCAN:
    FRAME_DEPTH: 10
NUM_OF_GPU_TRAIN: 1
TEST:
  DATA:
    BEGIN: 0.21
    CACHED_PATH: /media/laura/datasets/UBFC_rPPG/PreprocessedData/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse
    DATASET: UBFC-rPPG
    DATA_FORMAT: NDCHW
    DATA_PATH: /media/laura/datasets/UBFC_rPPG/DATASET_2
    DO_PREPROCESS: True
    END: 0.4
    EXP_DATA_NAME: UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse
    FILE_LIST_PATH: /media/laura/datasets/UBFC_rPPG/PreprocessedData/DataFileLists/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse_0.21_0.4.csv
    FILTERING:
      EXCLUSION_LIST: ['']
      SELECT_TASKS: False
      TASK_LIST: ['']
      USE_EXCLUSION_LIST: False
    FOLD:
      FOLD_NAME: 
      FOLD_PATH: 
    FS: 30
    INFO:
      EXERCISE: [True]
      GENDER: ['']
      GLASSER: [True]
      HAIR_COVER: [True]
      LIGHT: ['']
      MAKEUP: [True]
      MOTION: ['']
      SKIN_COLOR: [1]
    PREPROCESS:
      BIGSMALL:
        BIG_DATA_TYPE: ['']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9
        SMALL_DATA_TYPE: ['']
      CHUNK_LENGTH: 180
      CROP_FACE:
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
        DO_CROP_FACE: True
        LARGE_BOX_COEF: 1.5
        USE_LARGE_FACE_BOX: True
      DATA_AUG: ['None']
      DATA_TYPE: ['DiffNormalized', 'Standardized']
      DO_CHUNK: True
      LABEL_TYPE: DiffNormalized
      RESIZE:
        H: 72
        W: 72
      USE_PSUEDO_PPG_LABEL: False
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR']
  USE_LAST_EPOCH: True
TOOLBOX_MODE: train_and_test
TRAIN:
  BATCH_SIZE: 4
  DATA:
    BEGIN: 0.0
    CACHED_PATH: /media/laura/datasets/UBFC_rPPG/PreprocessedData/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse
    DATASET: UBFC-rPPG
    DATA_FORMAT: NDCHW
    DATA_PATH: /media/laura/datasets/UBFC_rPPG/DATASET_2
    DO_PREPROCESS: False
    END: 0.8
    EXP_DATA_NAME: UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse
    FILE_LIST_PATH: /media/laura/datasets/UBFC_rPPG/PreprocessedData/DataFileLists/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse_0.0_0.8.csv
    FILTERING:
      EXCLUSION_LIST: ['']
      SELECT_TASKS: False
      TASK_LIST: ['']
      USE_EXCLUSION_LIST: False
    FOLD:
      FOLD_NAME: 
      FOLD_PATH: 
    FS: 30
    INFO:
      EXERCISE: [True]
      GENDER: ['']
      GLASSER: [True]
      HAIR_COVER: [True]
      LIGHT: ['']
      MAKEUP: [True]
      MOTION: ['']
      SKIN_COLOR: [1]
    PREPROCESS:
      BIGSMALL:
        BIG_DATA_TYPE: ['']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9
        SMALL_DATA_TYPE: ['']
      CHUNK_LENGTH: 180
      CROP_FACE:
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
        DO_CROP_FACE: True
        LARGE_BOX_COEF: 1.5
        USE_LARGE_FACE_BOX: True
      DATA_AUG: ['None']
      DATA_TYPE: ['DiffNormalized', 'Standardized']
      DO_CHUNK: True
      LABEL_TYPE: DiffNormalized
      RESIZE:
        H: 72
        W: 72
      USE_PSUEDO_PPG_LABEL: False
  EPOCHS: 30
  LR: 0.009
  MODEL_FILE_NAME: UBFC_UBFC_deepphys
  OPTIMIZER:
    BETAS: (0.9, 0.999)
    EPS: 0.0001
    MOMENTUM: 0.9
UNSUPERVISED:
  DATA:
    BEGIN: 0.0
    CACHED_PATH: PreprocessedData/_SizeW128_SizeH128_ClipLength180_DataType_DataAugNone_LabelType_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse_unsupervised
    DATASET: 
    DATA_FORMAT: NDCHW
    DATA_PATH: 
    DO_PREPROCESS: False
    END: 1.0
    EXP_DATA_NAME: _SizeW128_SizeH128_ClipLength180_DataType_DataAugNone_LabelType_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse_unsupervised
    FILE_LIST_PATH: PreprocessedData/DataFileLists/_SizeW128_SizeH128_ClipLength180_DataType_DataAugNone_LabelType_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse_unsupervised_0.0_1.0.csv
    FILTERING:
      EXCLUSION_LIST: ['']
      SELECT_TASKS: False
      TASK_LIST: ['']
      USE_EXCLUSION_LIST: False
    FOLD:
      FOLD_NAME: 
      FOLD_PATH: 
    FS: 0
    INFO:
      EXERCISE: [True]
      GENDER: ['']
      GLASSER: [True]
      HAIR_COVER: [True]
      LIGHT: ['']
      MAKEUP: [True]
      MOTION: ['']
      SKIN_COLOR: [1]
    PREPROCESS:
      CHUNK_LENGTH: 180
      CROP_FACE:
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
        DO_CROP_FACE: True
        LARGE_BOX_COEF: 1.5
        USE_LARGE_FACE_BOX: True
      DATA_AUG: ['None']
      DATA_TYPE: ['']
      DO_CHUNK: True
      LABEL_TYPE: 
      RESIZE:
        H: 128
        W: 128
      USE_PSUEDO_PPG_LABEL: False
  METHOD: []
  METRICS: []
VALID:
  DATA:
    BEGIN: 0.8
    CACHED_PATH: /media/laura/datasets/UBFC_rPPG/PreprocessedData
    DATASET: UBFC-rPPG
    DATA_FORMAT: NDCHW
    DATA_PATH: /media/laura/datasets/UBFC_rPPG/DATASET_2
    DO_PREPROCESS: True
    END: 1.0
    EXP_DATA_NAME: 
    FILE_LIST_PATH: PreprocessedData/DataFileLists
    FILTERING:
      EXCLUSION_LIST: ['']
      SELECT_TASKS: False
      TASK_LIST: ['']
      USE_EXCLUSION_LIST: False
    FOLD:
      FOLD_NAME: 
      FOLD_PATH: 
    FS: 30
    INFO:
      EXERCISE: [True]
      GENDER: ['']
      GLASSER: [True]
      HAIR_COVER: [True]
      LIGHT: ['']
      MAKEUP: [True]
      MOTION: ['']
      SKIN_COLOR: [1]
    PREPROCESS:
      BIGSMALL:
        BIG_DATA_TYPE: ['']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9
        SMALL_DATA_TYPE: ['']
      CHUNK_LENGTH: 180
      CROP_FACE:
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
        DO_CROP_FACE: True
        LARGE_BOX_COEF: 1.5
        USE_LARGE_FACE_BOX: True
      DATA_AUG: ['None']
      DATA_TYPE: ['DiffNormalized', 'Standardized']
      DO_CHUNK: False
      LABEL_TYPE: DiffNormalized
      RESIZE:
        H: 72
        W: 72
      USE_PSUEDO_PPG_LABEL: False

Cached Data Path /media/laura/datasets/UBFC_rPPG/PreprocessedData/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse

File List Path /media/laura/datasets/UBFC_rPPG/PreprocessedData/DataFileLists/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse_0.0_0.8.csv
 train Preprocessed Dataset Length: 47

Testing uses last epoch, validation dataset is not required.

Preprocessing dataset...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [07:37<00:00, 57.23s/it]
Total Number of raw files preprocessed: 8

Cached Data Path /media/laura/datasets/UBFC_rPPG/PreprocessedData/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse

File List Path /media/laura/datasets/UBFC_rPPG/PreprocessedData/DataFileLists/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse_0.21_0.4.csv
 test Preprocessed Dataset Length: 33


====Training Epoch: 0====
Train epoch 0:  33%|█▋   | 4/12 [01:00<02:00, 15.04s/it, loss=0.802, lr=0.00039]
Traceback (most recent call last):
  File "/home/laura/Development/rPPG-Toolbox/main.py", line 288, in <module>
    train_and_test(config, data_loader_dict)
  File "/home/laura/Development/rPPG-Toolbox/main.py", line 78, in train_and_test
    model_trainer.train(data_loader_dict)
  File "/home/laura/Development/rPPG-Toolbox/neural_methods/trainer/DeepPhysTrainer.py", line 62, in train
    for idx, batch in enumerate(tbar):
  File "/home/laura/anaconda3/envs/rppg-toolbox/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/laura/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/laura/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "/home/laura/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/laura/.local/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/home/laura/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/laura/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/laura/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/laura/Development/rPPG-Toolbox/dataset/data_loader/BaseLoader.py", line 90, in __getitem__
    data = np.load(self.inputs[index])
  File "/home/laura/anaconda3/envs/rppg-toolbox/lib/python3.10/site-packages/numpy/lib/npyio.py", line 432, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "/home/laura/anaconda3/envs/rppg-toolbox/lib/python3.10/site-packages/numpy/lib/format.py", line 831, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 61936 into shape (180,72,72,6)
```
