### ISSUE TITLE
Bugs for processing MMPD dataset when the `DO_PREPROCESS` is set to False

### ISSUE THREAD

**Issue by Dylan-H-Wang** [ubicomplab/rPPG-Toolbox#210]
Hi,

I found the program will throw an error `ValueError: ('train', 'File list empty. Check preprocessed data folder exists and is not empty.')` when the config file set the`DO_PREPROCESS: False` for `MMPD` but not for `UBFC-rPPG`.

I located the bug happened at https://github.com/ubicomplab/rPPG-Toolbox/blob/53b84584c2501f40ac925e141e7b908d1013d002/dataset/data_loader/BaseLoader.py#L487

Since in https://github.com/ubicomplab/rPPG-Toolbox/blob/53b84584c2501f40ac925e141e7b908d1013d002/dataset/data_loader/MMPDLoader.py#L56 the dict key `index` is used for the video index of each subject instead of subject index. In the `UBFC-rPPGLoader`, the `index` is defined by `dirs = [{"index": re.search('subject(\d+)', data_dir).group(0), "path": data_dir} for data_dir in data_dirs]` which would include string `subject`, but this is not the case for `MMPDLoader` which I think cause this bug.

I hard-coded the block to solve this issue by changing two lines:
```python
    def build_file_list_retroactive(self, data_dirs, begin, end):
        """ If a file list has not already been generated for a specific data split build a list of files 
        used by the dataloader for the data split. Eg. list of files used for 
        train / val / test. Also saves the list to a .csv file.

        Args:
            data_dirs(List[str]): a list of video_files.
            begin(float): index of begining during train/val split.
            end(float): index of ending during train/val split.
        Returns:
            None (this function does save a file-list .csv file to self.file_list_path)
        """

        # get data split based on begin and end indices.
        data_dirs_subset = self.split_raw_data(data_dirs, begin, end)

        # generate a list of unique raw-data file names
        filename_list = []
        for i in range(len(data_dirs_subset)):
            # filename_list.append(data_dirs_subset[i]['index'])
            filename_list.append(data_dirs_subset[i]['subject'])
        filename_list = list(set(filename_list))  # ensure all indexes are unique

        # generate a list of all preprocessed / chunked data files
        file_list = []
        for fname in filename_list:
            # processed_file_data = list(glob.glob(self.cached_path + os.sep + "{0}_input*.npy".format(fname)))
            processed_file_data = list(glob.glob(self.cached_path + os.sep + "subject{0}_*_input*.npy".format(fname)))
            file_list += processed_file_data

        if not file_list:
            raise ValueError(self.dataset_name,
                             'File list empty. Check preprocessed data folder exists and is not empty.')

        file_list_df = pd.DataFrame(file_list, columns=['input_files'])
        os.makedirs(os.path.dirname(self.file_list_path), exist_ok=True)
        file_list_df.to_csv(self.file_list_path)  # save file list to .csv
```
commented lines are the original codes.

**Comment by yahskapar** [comment]
Hi @Dylan-H-Wang,

I'm unable to test this myself at the moment, just to clarify I understand the bug you noticed since the issue title and your post seem a bit confusing together: you are saying that when pre-processing a dataset for the first time, if someone forgets to set `DO_PREPROCESS` to `True`, the appropriate error is thrown for the MMPD dataset but *not* the UBFC-rPPG dataset? Or that even if you have the MMPD dataset preprocessed, the error is still shown?

Once you clarify I can look into this a bit further, though I'm not sure if the fixes you applied would work since it may cause a similar issue to pop up for other datasets which rely on that `index` key.

**Comment by Dylan-H-Wang** [comment]
Here is my `MMPD` data preprocessing YAML file:
```yaml
# use default train/val split with ratio 8/2
BASE: ['']
TRAIN:
  DATA:
    INFO:
      LIGHT: [1, 2, 3]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS: False                   # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "./data/MMPD/raw_data"          # Raw dataset path, need to be updated
    CACHED_PATH: "./data/MMPD/preprocessed_data"      # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "./data/MMPD/preprocessed_data/data_file_list"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['Standardized' ]
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    INFO:
      LIGHT: [1, 2, 3]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS: False                # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "./data/MMPD/raw_data"          # Raw dataset path, need to be updated
    CACHED_PATH: "./data/MMPD/preprocessed_data"      # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "./data/MMPD/preprocessed_data/data_file_list"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Standardized' ]
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  USE_LAST_EPOCH: False
  DATA:
    INFO:
      LIGHT: [1, 2, 3]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS: True                   # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "./data/MMPD/raw_data"          # Raw dataset path, need to be updated
    CACHED_PATH: "./data/MMPD/preprocessed_data"      # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "./data/MMPD/preprocessed_data/data_file_list"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized' ]
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
```
and I modified code a bit that `test_loader` will be run first then `train_loader` and `val_loder` so that it will preprocess the whole dataset first and generate `train_file_list` and `val_file_list` later without need to preprocessing the data again.

The bug happens after it preprocessed the whole dataset and generated the `test_file_list`. Since I specified the train and val data do not need `DO_PREPROCESS`, it will call `build_file_list_retroactive()` (the preprocessed file has been generated in the previous step), and then the mentioned bug will happen.
