### ISSUE TITLE
unable to access the log files in the directory (runs/exp)

### ISSUE THREAD

**Issue by znygithub** [ubicomplab/rPPG-Toolbox#266]
Hello,

I apologize for the inconvenience, but I have encountered two issues that I would like to seek your advice on:

1. During the preprocessing stage, I received a warning message. 
2. I am unable to access the log files in the directory (runs/exp).

Specifically, during the preprocessing phase, I keep getting the following warning: "Warning: More than one face is detected. Only the largest one will be cropped." However, all the videos in my dataset (UBFC_RPPG) feature a single person. I would like to inquire why this error is occurring.

> Warning: More than one faces are detected. Only cropping the biggest one.
>  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 35/42 [14:44<03:21, 28.85sRROR: No Face Detected
> Warning: More than one faces are detected. Only cropping the biggest one.
> Warning: More than one faces are detected. Only cropping the biggest one.
> Warning: More than one faces are detected. Only cropping the biggest one.
> Warning: More than one faces are detected. Only cropping the biggest one.
> Warning: More than one faces are detected. Only cropping the biggest one.
> Warning: More than one faces are detected. Only cropping the biggest one.
>  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 36/42 [15:05<02:39, 26.57sarning: More than one faces are detected. Only cropping the biggest one.
> Warning: More than one faces are detected. Only cropping the biggest one.
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42/42 [15:40<00:00, 22.40s
> Total Number of raw files preprocessed: 42
> 
> Cached Data Path E:\DATA_RPPG/UBFC-rppg\preprocessed\UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeStandardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_BackendHC_LargTrue_Large_size1.5_Dyamic_DetTrue_det_len30_Median_face_boxTrue
> 
> File List Path E:\DATA_RPPG/UBFC-rppg\preprocessed\DataFileLists\UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeStandardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_BaHC_Large_boxTrue_Large_size1.5_Dyamic_DetTrue_det_len30_Median_face_boxTrue_0.0_1.0.csv
>  test Preprocessed Dataset Length: 439

Additionally, when I attempted to test the preprocessed data, it failed to generate a PDF file. It appears that this issue might be due to the absence of the runs/exp folder in my files.
>  ===Testing===
> Testing uses pretrained model!
> Running model evaluation on the testing dataset!
> 100%|█████████████████████████████████████████| 110/110 [02:24<00:00,  1.31s/it]
> 
> Calculating metrics!
> 100%|███████████████████████████████████████████| 42/42 [00:22<00:00,  1.84it/s]
> FFT MAE (FFT Label): 2.9087611607142856 +/- 1.542169862676913
> FFT RMSE (FFT Label): 10.409081740227373 +/- 96.70726471524131
> FFT MAPE (FFT Label): 2.818213907041479 +/- 1.3511669244072901
> FFT Pearson (FFT Label): 0.8419704527681338 +/- 0.0853061774822644
> FFT SNR (FFT Label): 0.41872091466461353 +/- 1.2197019582934192 (dB)
> Traceback (most recent call last):
>   File "main.py", line 293, in <module>
>     test(config, data_loader_dict)
>   File "main.py", line 100, in test
>     model_trainer.test(data_loader_dict)
>   File "D:\桌面\code\rPPG-Toolbox\neural_methods\trainer\EfficientPhysTrainer.py", line 214, in test
>     calculate_metrics(predictions, labels, self.config)
>   File "D:\桌面\code\rPPG-Toolbox\evaluation\metrics.py", line 136, in calculate_metrics
>     compare.scatter_plot(
>   File "D:\桌面\code\rPPG-Toolbox\evaluation\BlandAltmanPy.py", line 116, in scatter_plot
>     plt.savefig(os.path.join(self.save_path, file_name),bbox_inches='tight', dpi=300)
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\pyplot.py", line 722, in savefig
>     res = fig.savefig(*args, **kwargs)
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\figure.py", line 2180, in savefig
>     self.canvas.print_figure(fname, **kwargs)
>     result = print_method(
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\backends\backend_pdf.py", line 2496, in print_pdf
>     file = PdfFile(filename, metadata=metadata)
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\backends\backend_pdf.py", line 432, in __init__
>     fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\cbook\__init__.py", line 432, in to_filehandle
>     fh = open(fname, flag, encoding=encoding)
> FileNotFoundError: [Errno 2] No such file or directory: 'runs/exp\\UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeStandardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_BackendHC_Large_boxTrue_Large_size1.BackendHC_Large_boxTrue_Large_size1.5_Dyamic_DetTrue_det_len30_Median_face_boxTrue\\bland_altman_plots\\PURE_EfficientPhys_UBFC-rPPG_FFT_BlandAltman_ScatterPlot.pdf'

**Comment by yahskapar** [comment]
Hi @znygithub,

The warning you're seeing should be totally fine. It simply means that multiple "faces" were detected, but it will always pick the largest face box that should ideally correspond to the actual, properly detected face rather than any smaller, adversarial patch of the image. You can verify that the face detection results are reasonable by visualizing the preprocessed data, for example by referring to [this section of our README](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#eyes-visualization-of-preprocessed-data).

As for your second issue, can you share the exact config file you're using as well as what operating system you have? My guess is it's the inconsistency with forward `/` and back `\` slashes both appearing in the save path seen in your error message. You should be able to remedy this by changing this portion of your config file:

```
LOG:
  PATH: runs/exp
```
to this:
```
LOG:
  PATH: runs\exp
```

**Comment by znygithub** [comment]
My system is Windows 10
my yaml is here:
```
BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: True
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "E:/DATA_RPPG/UBFC-rppg/unzip/UBFC_RPPG/UBFC_DATASET/DATASET_2"                     # Raw dataset path, need to be updated
    CACHED_PATH: "E:/DATA_RPPG/UBFC-rppg/preprocessed"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: True    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1 
LOG:
  PATH: runs\exp
MODEL:
  DROP_RATE: 0.2
  NAME: EfficientPhys
  EFFICIENTPHYS:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: 'FFT'        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH:   "./final_model_release/PURE_EfficientPhys.pth"

```
I change this portion of my config file:
```
LOG:
  PATH: runs/exp
```
to this:
```
LOG:
  PATH: runs\exp
```
but I still can't build runs\exp

This is  the result after running python main.py --config_file ./configs/infer_configs/PURE_UBFC-rPPG_EFFICIENTPHYS.yaml
> Cached Data Path E:/DATA_RPPG/UBFC-rppg/preprocessed\UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeStandardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_BackendHC_Large_boxTrue_Large_size1.5_Dyamic_DetTrue_det_len30_Median_face_boxTrue
> 
> File List Path E:/DATA_RPPG/UBFC-rppg/preprocessed\DataFileLists\UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeStandardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_BackendHC_Large_boxTrue_Large_size1.5_Dyamic_DetTrue_det_len30_Median_face_boxTrue_0.0_1.0.csv
>  test Preprocessed Dataset Length: 439
> 
> 
> ===Testing===
> Testing uses pretrained model!
> Running model evaluation on the testing dataset!
> 100%|█████████████████████████████████████████| 110/110 [01:35<00:00,  1.15it/s]
> 
> Calculating metrics!
> 100%|███████████████████████████████████████████| 42/42 [00:24<00:00,  1.68it/s]
> FFT MAE (FFT Label): 2.9087611607142856 +/- 1.542169862676913
> FFT RMSE (FFT Label): 10.409081740227373 +/- 96.70726471524131
> FFT MAPE (FFT Label): 2.818213907041479 +/- 1.3511669244072901
> FFT Pearson (FFT Label): 0.8419704527681338 +/- 0.0853061774822644
> FFT SNR (FFT Label): 0.41872091466461353 +/- 1.2197019582934192 (dB)
> Traceback (most recent call last):
>   File "main.py", line 293, in <module>
>     test(config, data_loader_dict)
>   File "main.py", line 100, in test
>     model_trainer.test(data_loader_dict)
>   File "D:\桌面\code\rPPG-Toolbox\neural_methods\trainer\EfficientPhysTrainer.py", line 214, in test
>     calculate_metrics(predictions, labels, self.config)
>   File "D:\桌面\code\rPPG-Toolbox\evaluation\metrics.py", line 136, in calculate_metrics
>     compare.scatter_plot(
>   File "D:\桌面\code\rPPG-Toolbox\evaluation\BlandAltmanPy.py", line 116, in scatter_plot
>     plt.savefig(os.path.join(self.save_path, file_name),bbox_inches='tight', dpi=300)
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\pyplot.py", line 722, in savefig
>     res = fig.savefig(*args, **kwargs)
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\figure.py", line 2180, in savefig
>     self.canvas.print_figure(fname, **kwargs)
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\backend_bases.py", line 2082, in print_figure
>     result = print_method(
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\backends\backend_pdf.py", line 2496, in print_pdf
>     file = PdfFile(filename, metadata=metadata)
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\backends\backend_pdf.py", line 432, in __init__
>     fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
>   File "D:\Anaconda\envs\rppg-toolbox\lib\site-packages\matplotlib\cbook\__init__.py", line 432, in to_filehandle
>     fh = open(fname, flag, encoding=encoding)
> **FileNotFoundError: [Errno 2] No such file or directory: 'runs\\exp\\UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataTypeStandardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_BackendHC_Large_boxTrue_Large_size1.5_Dyamic_DetTrue_det_len30_Median_face_boxTrue\\bland_altman_plots\\PURE_EfficientPhys_UBFC-rPPG_FFT_BlandAltman_ScatterPlot.pdf'**
